#install:
#  - ./gradlew assemble

language: android

android:
  components:
    - build-tools-27.0.3
    - android-27

addons:
  sonarcloud:
    organization: "vtraineau-github"
    token:
      secure: "a25c021edaee91dc99372faafd968212d58945fc"

script:
  - ./gradlew clean
  - ./gradlew sonarqube -Dsonar.projectKey=vtraineau_blokish-testing-travis -Dsonar.organization=vtraineau-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a25c021edaee91dc99372faafd968212d58945fc
  - set -ev
  - wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O opam
  - chmod ugo+x opam
  - ./opam init --yes --comp=4.01.0
  - eval `./opam config env`
  - ./opam install --yes sawja.1.5 atdgen.1.5.0 javalib.2.3a extlib.1.5.4
  - git clone https://github.com/facebook/infer.git
  - cd infer
  - ./build-infer.sh java
  - export PATH=`pwd`/infer/bin:$PATH
  - cd ..
  - infer run -- ./gradlew build
